### PR TITLE
🧪 Cedar Test Failure in MMELocationManagerTests.mm #170

### LINKED ISSUE #170: 🧪 Cedar Test Failure in MMELocationManagerTests.mm
**Context**
Checking for region monitoring startup.

**Assertions**
file:///Users/alfwatt/Source/mapbox-events-ios/Tests/MMELocationManagerTests.mm: test failure: -[_MMELocationManagerSpec MMELocationManagerDelegate_interaction_when_the_host_app_has_always_permissions_when_location_data_are_received_tells_the_location_manager_to_start_monitoring_for_region] failed: Expected <<CLLocationManager: 0x60200003cfb0>> to have received message <startMonitoringForRegion:>, with arguments: <CLCircularRegion (identifier:'MMELocationManagerRegionIdentifier.fence.center', center:<+0.00000000,+0.00000000>, radius:300.00m)> but received messages:
  setDelegate:<<nil>>
  setDelegate:<<MMELocationManager: 0x6060005d9620>>
  setDesiredAccuracy:<3000>
  setDistanceFilter:<5>
  startMonitoringVisits
  startUpdatingLocation
  monitoredRegions
  monitoredRegions

### PR DESCRIPTION
**Pull request by alfwatt**
Fixes: #170

### CODE REVIEW

File: Tests/MMELocationManagerTests.mm [hunk 1]
```diff
@@ -420,11 +420,6 @@ - (void)stopMonitoringRegions;
                     [locationManager startUpdatingLocation];
                     [locationManager locationManager:locationManagerInstance didUpdateLocations:@[movingLocation]];
                     locationManager.backgroundLocationServiceTimeoutTimer should_not be_nil;
-                });
-                
-                it(@"tells the location manager to start monitoring for region", ^{
-                    expectedRegion.notifyOnEntry = NO;
-                    expectedRegion.notifyOnExit = YES;
```
Comment (rclee) [inline Tests/MMELocationManagerTests.mm:427]: Why are we removing these configurations from the expected region? Is the region being returned different?

Comment (alfwatt) [reply Tests/MMELocationManagerTests.mm:427]: Because they are set in `establishRegionMonitoringForLocation` which is called by `locationManager:didUpdateLocations` in the beforeEach block.

**Review by rclee — APPROVED** [review]
