### PR TITLE
Fix null ptr access crash

### LINKED ISSUE #321: 🐞 [iOS] Crash: NSUserDefaults+MMEConfiguration.m - Line 338
**Configuration**
 - SDK Version 1.0.5
 - iOS Version: 14.7.1 and 14.8
 - Device: iPhone X and iPhone 11 Pro
 
**Steps to Reproduce**
We have Crashlytics reports from the App Store version of the app where it crashes in the SDK. I don't know the steps to reproduce since these are happening to our users in the wild. I can see, based on logs, that it happens at the launch of the app. 

**Logging**
Below is the Crashlytics report that we got, let me know how else I can help. 

Screen Shot 2021-10-11 at 4 33 10 PM

### PR DESCRIPTION
**Pull request by vayesh**
Fixes #321.

### CODE REVIEW

**Review by nagineni — APPROVED** [review]

File: Sources/MapboxMobileEvents/NSUserDefaults+MMEConfiguration.m [hunk 1]
```diff
@@ -335,6 +335,10 @@ - (NSString *)mme_userAgentString {
         for (uint32_t i = 0; i < infos->infoArrayCount; ++i) {
             struct dyld_image_info *imageInfo = infoArray + i;
 
+            if (imageInfo == 0 || imageInfo->imageFilePath == 0) {
```
Comment (mr1sunshine) [inline Sources/MapboxMobileEvents/NSUserDefaults+MMEConfiguration.m]: Should we use `NULL` instead of `0`?
