### PR TITLE
TrustKit fix

### LINKED ISSUE #66: TrustKit nullability warnings in Xcode 10/iOS 12
We should update TrustKit to the latest version, if only to pull in https://github.com/datatheorem/TrustKit/pull/172, which fixes the following build warnings in Xcode 10:

> vendor/TrustKit/Pinning/TSKSPKIHashCache.m:306:33: null passed to a callee that requires a non-null argument [-Wnonnull]

> vendor/TrustKit/Pinning/TSKSPKIHashCache.m:342:37: null passed to a callee that requires a non-null argument [-Wnonnull]

### LINKED ISSUE #71: ThreadSanitizer: data race TrustKit.m:51 in MGL_TSKLog
Running the thread sanitizer on gl-native with mapbox-mobile-events at 33476cafc3669d151411a9c52d5feaaf31d628da (0.5.1) results in:

```
==================
WARNING: ThreadSanitizer: data race (pid=2230)
  Read of size 8 at 0x0001261137a0 by thread T18:
    #0 MGL_TSKLog TrustKit.m:51 (Mapbox:x86_64+0x311ff9)
    #1 MGL_verifyPublicKeyPin ssl_pin_verifier.m:67 (Mapbox:x86_64+0x72bdba)
    #2 -[MGL_TSKPinningValidator evaluateTrust:forHostname:] TSKPinningValidator.m:147 (Mapbox:x86_64+0x17f6a5)
    #3 -[MGL_TSKPinningValidator handleChallenge:completionHandler:] TSKPinningValidator.m:224 (Mapbox:x86_64+0x18049a)
    #4 -[MGL_MMENSURLSessionWrapper URLSession:didReceiveChallenge:completionHandler:] MMENSURLSessionWrapper.m:50 (Mapbox:x86_64+0x64db2f)
    #5 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ <null>:9644672 (Foundation:x86_64+0x3b362)
    #6 _dispatch_client_callout <null>:9644672 (libdispatch.dylib:x86_64+0x3708)

  Previous write of size 8 at 0x0001261137a0 by main thread:
    #0 +[MGL_TrustKit setLoggerBlock:] TrustKit.m:239 (Mapbox:x86_64+0x314d2c)
    #1 +[MGL_MMETrustKitProvider trustKitWithUpdatedConfiguration:] MMETrustKitProvider.m:12 (Mapbox:x86_64+0x34d4a8)
    #2 -[MGL_MMENSURLSessionWrapper init] MMENSURLSessionWrapper.m:21 (Mapbox:x86_64+0x64c7ba)
    #3 -[MGL_MMEAPIClient initWithAccessToken:userAgentBase:hostSDKVersion:] MMEAPIClient.m:32 (Mapbox:x86_64+0x34e77d)
    #4 -[MGL_MMEEventsManager initializeWithAccessToken:userAgentBase:hostSDKVersion:] MMEEventsManager.m:78 (Mapbox:x86_64+0x66a24c)
    #5 __40+[MGLMapboxEvents setupWithAccessToken:]_block_invoke MGLMapboxEvents.m:142 (Mapbox:x86_64+0x756ba8)
    #6 __tsan::invoke_and_release_block(void*) <null>:9644672 (libclang_rt.tsan_iossim_dynamic.dylib:x86_64+0x622bb)
    #7 _dispatch_client_callout <null>:9644672 (libdispatch.dylib:x86_64+0x3708)
    #8 +[XCTestCase(Failures) performFailableBlock:shouldInterruptTest:] <null>:9644672 (XCTest:x86_64+0x7dae2)

  Location is global 'MGL__loggerBlock' at 0x0001261137a0 (Mapbox+0x000006eb97a0)

  Thread T18 (tid=12588, running) is a GCD worker thread

SUMMARY: ThreadSanitizer: data race TrustKit.m:51 in MGL_TSKLog
==================
```

[Full log](https://163946-16286131-gh.circle-artifacts.com/0/Users/distiller/project/build/logs/xcodebuild-2018-09-25_220233.log) from [gl-native’s ios-sanitize job](https://circleci.com/gh/mapbox/mapbox-gl-native/163946#artifacts/containers/0). Though not necessarily a crash, it is crashing/failing the tests that trigger this sanitizer warning:

> Restarting after unexpected exit or crash in MGLStyleTests/testAddingSourceOfTypeABeforeSourceOfTypeBWithSameIdentifier; summary will include totals from previous launches.

/cc @rclee @julianrex

### PR DESCRIPTION
**Pull request by rclee**
Changes to TrustKit to fix [nullability warnings](https://github.com/mapbox/mapbox-events-ios/issues/66) in Xcode 10/iOS 12 and fix [a data race](https://github.com/mapbox/mapbox-events-ios/issues/71) with TrustKit's logging. The data race issue is only an issue in non-release builds, in release builds the logger is disabled.

### CODE REVIEW

**Review by friedbunny — DISMISSED** [review]
Thanks! If possible, it’d be nice to get this into `gl-native` before tomorrow’s `ios-v4.5.0-beta.1`.

File: vendor/TrustKit/Pinning/TSKSPKIHashCache.m [hunk 1]
```diff
@@ -303,7 +303,8 @@ - (NSData *)getPublicKeyDataFromCertificate_unified:(SecCertificateRef)certifica
     SecTrustCreateWithCertificates(certificate, policy, &trust);
     
     // Get a public key reference for the certificate from the trust
-    SecTrustEvaluate(trust, NULL);
+    SecTrustResultType result;
+    SecTrustEvaluate(trust, &result);
```
[the remark this answers is not in the document]
Comment (friedbunny) [reply vendor/TrustKit/Pinning/TSKSPKIHashCache.m]: This is pulled from https://github.com/datatheorem/TrustKit/pull/172 — if we deviate from that, we should consider upstreaming the fix.

**Comment by rclee** [comment]
Pushed up the changes we worked on @julianrex and added an additional test for when TrustKit will evaluate a challenge. Would be great to get  👀 on this PR again. Hopefully we can put this horse out to pasture... 🐴

File: MapboxMobileEventsTests/APIServiceURLProtocol.h [hunk 2]
```diff
@@ -0,0 +1,9 @@
+#import <Foundation/Foundation.h>
+
+NS_ASSUME_NONNULL_BEGIN
+
+@interface APIServiceURLProtocol : NSURLProtocol <NSURLAuthenticationChallengeSender>
```
Comment (julianrex) [inline MapboxMobileEventsTests/APIServiceURLProtocol.h]: I don't think this file is used/needed any more?

File: MapboxMobileEventsTests/MMEAPIClientTests.mm [hunk 3]
```diff
@@ -43,6 +47,136 @@ - (void)setupUserAgent;
...
+                }];
+                
+                while (!completionBlockCalled) {
+                    NSDate *futureDate = [NSDate dateWithTimeIntervalSinceNow:0.1];
+                    [[NSRunLoop currentRunLoop] runUntilDate:futureDate];
+                }
+            });
+            
+            it(@"should be on background queue", ^{
+                isMainThread should be_falsy;
```
Comment (julianrex) [inline MapboxMobileEventsTests/MMEAPIClientTests.mm]: The completion block should always be called on the main thread, so is this failing?

Comment (julianrex) [reply MapboxMobileEventsTests/MMEAPIClientTests.mm]: i.e. I think this `should be_truthy`

File: MapboxMobileEvents/MMENSURLSessionWrapper.m [hunk 4]
```diff
@@ -46,12 +46,36 @@ - (void)processRequest:(NSURLRequest *)request completionHandler:(void (^)(NSDat
...
-    // Call into TrustKit here to do pinning validation
-    if (![self.trustKit.pinningValidator handleChallenge:challenge completionHandler:completionHandler]) {
-        // TrustKit did not handle this challenge: perhaps it was not for server trust
-        // or the domain was not pinned. Fall back to the default behavior
-        completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
-    }
+    __block void (^completion)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable) = nil;
+    
+    completion = ^(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * _Nullable credential){
+        dispatch_async(dispatch_get_main_queue(), ^{
```
Comment (julianrex) [inline MapboxMobileEvents/MMENSURLSessionWrapper.m:52]: For comments below - the completion block is dispatched to the main queue (on the main thread), which is what we want.

**Review by julianrex — DISMISSED** [review]
Looks good from the code side. You may want someone more familiar with Cedar to check on the tests.

**Comment by rclee** [comment]
Thanks so much @julianrex 🙇 -- @akitchen ? Mind giving it a once over? 💚

File: MapboxMobileEventsTests/MMEAPIClientTests.mm [hunk 5]
```diff
@@ -43,6 +46,136 @@ - (void)setupUserAgent;
...
+                NSURLAuthenticationChallenge *challenge = [[NSURLAuthenticationChallenge alloc] initWithProtectionSpace:space proposedCredential:nil previousFailureCount:0 failureResponse:nil error:nil sender:((DelegateTestClass *)delegateFake)];
+                
+                [sessionWrapper URLSession:urlSession didReceiveChallenge:challenge completionHandler:^(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable) {
+                    isMainThread = [NSThread isMainThread];
+                    completionBlockCalled = true;
+                }];
+                
+                while (!completionBlockCalled) {
+                    NSDate *futureDate = [NSDate dateWithTimeIntervalSinceNow:0.1];
+                    [[NSRunLoop currentRunLoop] runUntilDate:futureDate];
```
Comment (akitchen) [inline MapboxMobileEventsTests/MMEAPIClientTests.mm]: if this test were to break it would spin the while loop forever, which may or may not be a concern. have you considered failing it after a timeout?

File: MapboxMobileEventsTests/MMEAPIClientTests.mm [hunk 6]
```diff
@@ -43,6 +46,136 @@ - (void)setupUserAgent;
...
+                NSURLAuthenticationChallenge *challenge = [[NSURLAuthenticationChallenge alloc] init];
+
+                dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
+                    [sessionWrapper URLSession:urlSession didReceiveChallenge:challenge completionHandler:^(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable) {
+                        isMainThread = [NSThread isMainThread];
+                        completionBlockCalled = true;
+                    }];
+                });
+                
+                while (!completionBlockCalled) {
```
Comment (akitchen) [inline MapboxMobileEventsTests/MMEAPIClientTests.mm]: Same as above. Have you tried dispatching this synchronously, or does it block?

**Comment by akitchen** [comment]
Looks good to me, although you might consider either a synchronous dispatch or using a dispatch_semaphore instead of the while loops in the tests.

**Comment by rclee** [comment]
I've added dispatch_semaphore and this seems to be operating as expected. Let me know how that looks 👀

**Review by alfwatt — APPROVED** [review]

File: MapboxMobileEventsTests/MMEAPIClientTests.mm [hunk 7]
```diff
@@ -43,6 +47,145 @@ - (void)setupUserAgent;
...
+                while (dispatch_semaphore_wait(semaphore, DISPATCH_TIME_NOW)) {
+                    [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode beforeDate:[NSDate dateWithTimeIntervalSinceNow:10]];
+                }
+            });
+            
+            it(@"should be on main queue", ^{
+                isMainThread should be_truthy;
+            });
+            
+            it(@"should receive challenge", ^{
```
Comment (akitchen) [inline MapboxMobileEventsTests/MMEAPIClientTests.mm:87]: Hey, sorry I'm late to the party here, but this isn't a particularly valuable assertion, since you called this method yourself in the `beforeEach()`

Instead, it seems that what we care about is that TrustKit's pinning validator gets to handle the challenge ([link](https://github.com/mapbox/mapbox-events-ios/blob/5075b42512ca8675a77b8fd85f0f629eb22c93c3/MapboxMobileEvents/MMENSURLSessionWrapper.m#L73)) and that the inner completion is executed on the main queue. You've got the main queue (thread) part handled, but I'd recommend not spying on the session wrapper, and instead figuring out how to assert that the pinning validator was called as expected (since that's the seam into 3rd party code we care about)

... and if the pinning validator hits the network or does async work of its own, I'd recommend injecting a fake that doesn't introduce that non-determinism into the test suite.

Comment (alfwatt) [reply MapboxMobileEventsTests/MMEAPIClientTests.mm:87]: Good point: https://github.com/mapbox/mobile-telemetry/issues/291

Comment (rclee) [reply MapboxMobileEventsTests/MMEAPIClientTests.mm:87]: Fair point, these tests stopped being valuable when we changed directions and I failed to notice that. I'll make a new PR to fix this.
